# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'strategy_software_v3.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1017)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_DockGraphContainer = QtWidgets.QWidget(self.centralwidget)
        self.widget_DockGraphContainer.setGeometry(QtCore.QRect(160, 30, 1751, 881))
        self.widget_DockGraphContainer.setObjectName("widget_DockGraphContainer")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 391, 27))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 3, 0, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_plotData = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_plotData.setObjectName("pushButton_plotData")
        self.horizontalLayout.addWidget(self.pushButton_plotData)
        self.pushButton_ResetVariables = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_ResetVariables.setObjectName("pushButton_ResetVariables")
        self.horizontalLayout.addWidget(self.pushButton_ResetVariables)
        self.pushButton_addData = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_addData.setObjectName("pushButton_addData")
        self.horizontalLayout.addWidget(self.pushButton_addData)
        self.pushButton_AddIndicator = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_AddIndicator.setObjectName("pushButton_AddIndicator")
        self.horizontalLayout.addWidget(self.pushButton_AddIndicator)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 141, 881))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_checkBoxesVariables = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_checkBoxesVariables.setContentsMargins(0, 0, 0, 0)
        self.formLayout_checkBoxesVariables.setHorizontalSpacing(6)
        self.formLayout_checkBoxesVariables.setVerticalSpacing(0)
        self.formLayout_checkBoxesVariables.setObjectName("formLayout_checkBoxesVariables")
        self.PriceCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.PriceCheckBox.setObjectName("PriceCheckBox")
        self.formLayout_checkBoxesVariables.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.PriceCheckBox)
        self.Config_Price = QtWidgets.QToolButton(self.formLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/settings_black_18x18.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Config_Price.setIcon(icon)
        self.Config_Price.setObjectName("Config_Price")
        self.formLayout_checkBoxesVariables.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Config_Price)
        self.VolumeCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.VolumeCheckBox.setObjectName("VolumeCheckBox")
        self.formLayout_checkBoxesVariables.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.VolumeCheckBox)
        self.Config_Volume = QtWidgets.QToolButton(self.formLayoutWidget)
        self.Config_Volume.setIcon(icon)
        self.Config_Volume.setObjectName("Config_Volume")
        self.formLayout_checkBoxesVariables.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Config_Volume)
        self.checkBox_ToggleAutoRange = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ToggleAutoRange.setGeometry(QtCore.QRect(1789, 6, 111, 21))
        self.checkBox_ToggleAutoRange.setObjectName("checkBox_ToggleAutoRange")
        self.pushButton_GraphConfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_GraphConfig.setGeometry(QtCore.QRect(1706, 4, 76, 23))
        self.pushButton_GraphConfig.setObjectName("pushButton_GraphConfig")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuChart = QtWidgets.QMenu(self.menubar)
        self.menuChart.setObjectName("menuChart")
        self.menuStrategy = QtWidgets.QMenu(self.menubar)
        self.menuStrategy.setObjectName("menuStrategy")
        self.menuTrading_Accounts = QtWidgets.QMenu(self.menubar)
        self.menuTrading_Accounts.setObjectName("menuTrading_Accounts")
        self.menuLabelling = QtWidgets.QMenu(self.menubar)
        self.menuLabelling.setObjectName("menuLabelling")
        self.menuData_Science_Tools = QtWidgets.QMenu(self.menubar)
        self.menuData_Science_Tools.setObjectName("menuData_Science_Tools")
        self.menuMachine_Learning = QtWidgets.QMenu(self.menubar)
        self.menuMachine_Learning.setObjectName("menuMachine_Learning")
        self.menuDeep_Learning = QtWidgets.QMenu(self.menubar)
        self.menuDeep_Learning.setObjectName("menuDeep_Learning")
        self.menuIndicator = QtWidgets.QMenu(self.menubar)
        self.menuIndicator.setObjectName("menuIndicator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_New_Data = QtWidgets.QAction(MainWindow)
        self.actionImport_New_Data.setObjectName("actionImport_New_Data")
        self.actionPlot_Data = QtWidgets.QAction(MainWindow)
        self.actionPlot_Data.setObjectName("actionPlot_Data")
        self.actionUnplot_Data = QtWidgets.QAction(MainWindow)
        self.actionUnplot_Data.setObjectName("actionUnplot_Data")
        self.actionClear_Indicators = QtWidgets.QAction(MainWindow)
        self.actionClear_Indicators.setObjectName("actionClear_Indicators")
        self.actionCreate_New_Strategy = QtWidgets.QAction(MainWindow)
        self.actionCreate_New_Strategy.setObjectName("actionCreate_New_Strategy")
        self.actionPlot_Strategy = QtWidgets.QAction(MainWindow)
        self.actionPlot_Strategy.setObjectName("actionPlot_Strategy")
        self.actionBacktest_Strategy = QtWidgets.QAction(MainWindow)
        self.actionBacktest_Strategy.setObjectName("actionBacktest_Strategy")
        self.actionAdd_New_Account = QtWidgets.QAction(MainWindow)
        self.actionAdd_New_Account.setObjectName("actionAdd_New_Account")
        self.actionShow_Accounts = QtWidgets.QAction(MainWindow)
        self.actionShow_Accounts.setObjectName("actionShow_Accounts")
        self.actionDeploy_Strategy = QtWidgets.QAction(MainWindow)
        self.actionDeploy_Strategy.setObjectName("actionDeploy_Strategy")
        self.actionSave_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Data.setObjectName("actionSave_Data")
        self.actionOpen_Work = QtWidgets.QAction(MainWindow)
        self.actionOpen_Work.setObjectName("actionOpen_Work")
        self.actionSave_Work = QtWidgets.QAction(MainWindow)
        self.actionSave_Work.setObjectName("actionSave_Work")
        self.actionCreate_New_Work = QtWidgets.QAction(MainWindow)
        self.actionCreate_New_Work.setObjectName("actionCreate_New_Work")
        self.actionSave_Work_as = QtWidgets.QAction(MainWindow)
        self.actionSave_Work_as.setObjectName("actionSave_Work_as")
        self.actionLoad_Work = QtWidgets.QAction(MainWindow)
        self.actionLoad_Work.setObjectName("actionLoad_Work")
        self.actionCreate_Indicator = QtWidgets.QAction(MainWindow)
        self.actionCreate_Indicator.setObjectName("actionCreate_Indicator")
        self.menuFile.addAction(self.actionImport_New_Data)
        self.menuChart.addAction(self.actionCreate_New_Work)
        self.menuChart.addAction(self.actionLoad_Work)
        self.menuChart.addAction(self.actionSave_Work)
        self.menuChart.addAction(self.actionSave_Work_as)
        self.menuStrategy.addAction(self.actionCreate_New_Strategy)
        self.menuStrategy.addAction(self.actionPlot_Strategy)
        self.menuStrategy.addAction(self.actionBacktest_Strategy)
        self.menuTrading_Accounts.addAction(self.actionAdd_New_Account)
        self.menuTrading_Accounts.addAction(self.actionShow_Accounts)
        self.menuTrading_Accounts.addAction(self.actionDeploy_Strategy)
        self.menuIndicator.addAction(self.actionCreate_Indicator)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuChart.menuAction())
        self.menubar.addAction(self.menuIndicator.menuAction())
        self.menubar.addAction(self.menuStrategy.menuAction())
        self.menubar.addAction(self.menuTrading_Accounts.menuAction())
        self.menubar.addAction(self.menuLabelling.menuAction())
        self.menubar.addAction(self.menuData_Science_Tools.menuAction())
        self.menubar.addAction(self.menuMachine_Learning.menuAction())
        self.menubar.addAction(self.menuDeep_Learning.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_plotData.setText(_translate("MainWindow", "Plot Data"))
        self.pushButton_ResetVariables.setText(_translate("MainWindow", "Reset Variables"))
        self.pushButton_addData.setText(_translate("MainWindow", "Add Data"))
        self.pushButton_AddIndicator.setText(_translate("MainWindow", "Add Indicator"))
        self.PriceCheckBox.setText(_translate("MainWindow", "Price"))
        self.Config_Price.setText(_translate("MainWindow", "..."))
        self.VolumeCheckBox.setText(_translate("MainWindow", "Volume"))
        self.Config_Volume.setText(_translate("MainWindow", "..."))
        self.checkBox_ToggleAutoRange.setText(_translate("MainWindow", "Toggle Auto Range"))
        self.pushButton_GraphConfig.setText(_translate("MainWindow", "Graph Config"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuChart.setTitle(_translate("MainWindow", "Work"))
        self.menuStrategy.setTitle(_translate("MainWindow", "Strategy"))
        self.menuTrading_Accounts.setTitle(_translate("MainWindow", "Trading Accounts"))
        self.menuLabelling.setTitle(_translate("MainWindow", "Labelling"))
        self.menuData_Science_Tools.setTitle(_translate("MainWindow", "Data Science Tools"))
        self.menuMachine_Learning.setTitle(_translate("MainWindow", "Machine Learning"))
        self.menuDeep_Learning.setTitle(_translate("MainWindow", "Deep Learning"))
        self.menuIndicator.setTitle(_translate("MainWindow", "Indicator"))
        self.actionImport_New_Data.setText(_translate("MainWindow", "Import New Data"))
        self.actionPlot_Data.setText(_translate("MainWindow", "Plot Data"))
        self.actionUnplot_Data.setText(_translate("MainWindow", "Unplot Data"))
        self.actionClear_Indicators.setText(_translate("MainWindow", "Clear Indicators"))
        self.actionCreate_New_Strategy.setText(_translate("MainWindow", "Create New Strategy"))
        self.actionPlot_Strategy.setText(_translate("MainWindow", "Plot Strategy"))
        self.actionBacktest_Strategy.setText(_translate("MainWindow", "Backtest Strategy"))
        self.actionAdd_New_Account.setText(_translate("MainWindow", "Add New Account"))
        self.actionShow_Accounts.setText(_translate("MainWindow", "Show Accounts"))
        self.actionDeploy_Strategy.setText(_translate("MainWindow", "Deploy Strategy"))
        self.actionSave_Data.setText(_translate("MainWindow", "Save Data"))
        self.actionOpen_Work.setText(_translate("MainWindow", "Open Work"))
        self.actionSave_Work.setText(_translate("MainWindow", "Save Work"))
        self.actionCreate_New_Work.setText(_translate("MainWindow", "Create New Work"))
        self.actionSave_Work_as.setText(_translate("MainWindow", "Save Work as"))
        self.actionLoad_Work.setText(_translate("MainWindow", "Load Work"))
        self.actionCreate_Indicator.setText(_translate("MainWindow", "Create Indicator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
